### ISSUE TITLE
support Edystone and ibeacon?

### ISSUE THREAD

**Issue by mshanak** [demetrio812/nativescript-ibeacon#1]
hello
does this plugin support all beacon protocols ( Edystone,iBeacon)?

**Comment by demetrio812** [comment]
it only works for ibeacons at the moment, also it's still a pre-release, the final release will be finished soon

**Comment by demetrio812** [comment]
Hello, I've now updated a good version for iOS and Android, no support for Eddystone yet but the iBeacon support is ready, please test it and open an issue if you spot anything, cheers

**Comment by mshanak** [comment]
greate 👍 
but i am facing a problim when importing classes as described in readme file ,

![screen shot 2017-05-26 at 9 08 18 am](https://cloud.githubusercontent.com/assets/964266/26482977/1610a548-41f3-11e7-89b6-f42db4f0c314.png)

**Comment by demetrio812** [comment]
Please next time open another issue for a new topic, try this import and let me know:

```
import {
    Beacon,
    BeaconCallback,
    BeaconRegion,
    BeaconLocationOptions,
    BeaconLocationOptionsIOSAuthType,
    BeaconLocationOptionsAndroidAuthType
} from "nativescript-ibeacon/nativescript-ibeacon.common";
```
