### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by itcozum** [demetrio812/nativescript-ibeacon#10]
hi,

I'm planning to use your plugin for my ibeacon Advertising broadcasting project; but I'm afraid can't see any method or function for this purposes. Can u help?

Best Regards,
Nelly

**Comment by demetrio812** [comment]
Hello,
if you need to advertise, please check this plugin I've made: https://github.com/demetrio812/nativescript-virtual-ibeacon

Reopen if it's not what you meant...

Cheers,
Dem
