### ISSUE TITLE
Code with javascript

### ISSUE THREAD

**Issue by sandrolain** [demetrio812/nativescript-ibeacon#11]
Hi all
Can I develop with this plugin in javascript rather than with typescript?
Exists some examples?

Sorry for the stupid question, they are the first weapons with Nativescript but very practical with javascript. Otherwise if anyone knows a quick guide to the typescript I would be grateful.

Thanks!

**Comment by demetrio812** [comment]
Hello, yes you can but I don't have any example I'm afraid, however it's not that different from typescript, you need to check the native script website documentation for that, also quick guides on typescript are all over the web

Thanks,
Dem
