### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by mshanak** [demetrio812/nativescript-ibeacon#2]
i think you need to change the path of the ibeacon plugin in demo package.json 

![screen shot 2017-05-26 at 9 40 12 am](https://cloud.githubusercontent.com/assets/964266/26483803/8f880994-41f7-11e7-9d16-df2ebb89f926.png)

**Comment by demetrio812** [comment]
Hello,
what command are you using to build and run the demo?

If you use the predefined command the path will be inserted automatically, try with this command from the root folder:

```
 npm run demo.ios
```

Thanks

**Comment by mshanak** [comment]
still facing a problem running the demo 

![screen shot 2017-05-27 at 1 39 00 pm](https://cloud.githubusercontent.com/assets/964266/26520789/f25f6252-42e1-11e7-9168-157b1bdb10e9.png)

**Comment by demetrio812** [comment]
Hello,
it looks like you didn't do `npm install` before running the script...

Also please use the updated dependencies I've just committed...

**Comment by demetrio812** [comment]
Hello, did you test it?

Dem

**Comment by demetrio812** [comment]
Closing this as it should work, open a new issue in case you find something more, thanks!
