### ISSUE TITLE
no beacon discovered in Android

### ISSUE THREAD

**Issue by mshanak** [demetrio812/nativescript-ibeacon#3]
hello,

i have built a new app , it works fine on IOS and show the beacons , but when runnign the same app on android it start scanning but no beacon discovered ,

![screen shot 2017-06-01 at 3 36 17 pm](https://cloud.githubusercontent.com/assets/964266/26679980/19100a12-46e0-11e7-9b6f-0708fe198153.png)

**Comment by demetrio812** [comment]
Can you check if you have enabled the Location permissions for the demo app? 

Thanks,
Dem

**Comment by demetrio812** [comment]
Hello,
Any update on this? It works for me, no problems...

Dem

**Comment by mshanak** [comment]
still not working on samsung galaxy note 5 :(

**Comment by demetrio812** [comment]
It should not be related to the phone make, what OS version do you have? Did you check the permissions?

**Comment by demetrio812** [comment]
closing this as no replies for a while

**Comment by mshanak** [comment]
updated to version 0.8, now it works 👍 

great job, thank you
