### ISSUE TITLE
Demo not reading the eddystone information

### ISSUE THREAD

**Issue by deividfortuna** [demetrio812/nativescript-ibeacon#6]
Hi, I'm pretty new in nativescript and ibeacons.

I'm trying to run your demo in my android device, and when I turn on my eddystone the only thing that I get on my terminal is this:

`JS: Hello World Model constructed
JS: constructor
JS: Already authorised
JS: beaconManager created
JS: onBeaconServiceConnect
JS: onBeaconManagerReady
JS: startRanging
JS: startRangingBeaconsInRegion
JS: startMonitoring
JS: didDetermineStateForRegion
JS: 0
JS: id1: 2f234454-cf6d-4a0f-adf2-f4911ba9ffa6 id2: null id3: null
`

Seems that the method `didRangeBeaconsInRegion` is not been invoked.

**Comment by demetrio812** [comment]
Hello,
there is no support for Eddystone yet, only iBeacon...hopefully in a near future when I've got some time...

Pull requests are welcome ;)

Closing...
